name: GitHubBuild

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.2', '7.3', '7.4', '8.0' ]

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        tools: composer

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: setup templates_c
      run: mkdir templates_c || true

    - name: touch config.local.php
      run: touch config.local.php && php -v

    - name: Install dependencies
      run: composer install --prefer-dist -n

    - name: Build/test
      run: composer build

    - name: setup coveralls
      run: mkdir -p build/logs || true

    - name: Coveralls
      run: vendor/bin/coveralls ./clover.xml || true
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

